### ISSUE TITLE
ViewModel state

### ISSUE THREAD

**Issue by tmtron** [manuelvicnt/RxJava2-MVVM-Android-Structure#2]
Shouldn't the methods in [RegistrationObserver](https://github.com/manuelvicnt/RxJava2-MVVM-Android-Structure/blob/a56a05aaadb3b1f51272f6472cfab2f4fd42e6d9/app/src/main/java/com/manuelvicnt/rxjava2_mvvm_android_structure/registration/RegistrationViewModel.java#L118) call `super()`?

Otherwise the [requestState](url) in [NetworkViewModel](url) can never be `REQUEST_SUCCEEDED` or `REQUEST_FAILURE`, right?

**Comment by manuelvicnt** [comment]
You're right! Thanks for your contribution :)
